modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Chisel-Team/ConnectedTexturesMod/issues/"

[[mods]]
    modId="ctm"
    version="${file.jarVersion}"
    displayName="ConnectedTexturesMod"
    displayURL="https://chisel.team/ctm"
    #logoFile="examplemod.png"
    authors="tterrag, Drullkus, minecreatr"
    description='''
    Allows resource packs to add connected textures, emissive rendering, and much more.
    '''

[[dependencies.ctm]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.108,)"
    ordering="NONE"
    side="BOTH"